sudo: required
services:
- docker
before_install:
- docker build -t $DOCKER_IMAGE .
script:
- docker run -it --rm $DOCKER_IMAGE py.test
env:
  global:
  - SERVER_GROUP=demo_group
  - HALO_API_HOSTNAME=api.cloudpassage.com
  - HALO_API_PORT=443
  - DOCKER_IMAGE="awilson/don-dash:latest"

